### ISSUE TITLE
不是问题，交流

### ISSUE THREAD

**Issue by niniloveyou** [Fly-Mix/flr-cli#1]
感觉这种实现方式工作量比较大，且依赖于项目安装脚本，监控资源文件变更需要启动服务

建议通过写 IDE 插件的方式实现

**Comment by CodeEagle** [comment]
@niniloveyou 
有 IDE 插件的
[VSCode](https://github.com/Fly-Mix/flr-vscode-extension)
[AS](https://github.com/Fly-Mix/flr-as-plugin)
