### ISSUE TITLE
生成的图片路径多了一个/是为什么

### ISSUE THREAD

**Issue by Ziven-n** [Fly-Mix/flr-cli#10]
assets:
  - assets/images//300.jpg
  - assets/images//N.png
  - assets/images//VIP.png
  - assets/images//Y.png
  - assets/images//aboutking.png
  - assets/images//acebg.png
  - assets/images//acecpt.png
  - assets/images//acsmbg.png
跟图片命名有关系吗

**Comment by YK-Unit** [comment]
> assets:
> 
> * assets/images//300.jpg
> * assets/images//N.png
> * assets/images//VIP.png
> * assets/images//Y.png
> * assets/images//aboutking.png
> * assets/images//acebg.png
> * assets/images//acecpt.png
> * assets/images//acsmbg.png
>   跟图片命名有关系吗

1. 你图片的命名是怎么样的呢？可以发出来看看吗
2. 从生成看，这多出来的 / 像是来自图片名称本身

**Comment by Ziven-n** [comment]
> 1. 你图片的命名是怎么样的呢？可以发出来看看吗
> 2. 从生成看，这多出来的 / 像是来自图片名称本身

命名是正常的命名
300.jpg
acebg.png
cache.png
等等
只是有一些比如数字开头或者大写字母开头的命名

**Comment by Ziven-n** [comment]
我这边是一个旧项目才这个样子在命名的基础上多出一个/，其他项目是正常的，旧项目相比新项目的话最外层多一个文件夹

**Comment by Ziven-n** [comment]
![](https://github.com/Ziven-n/images/blob/main/%E6%88%AA%E5%B1%8F2023-11-15%2017.09.05.png)

**Comment by Ziven-n** [comment]
![](https://github.com/Ziven-n/images/blob/main/%E6%88%AA%E5%B1%8F2023-11-15%2017.09.05.png)

**Comment by Ziven-n** [comment]
![截屏2023-11-15 17 09 05](https://github.com/Fly-Mix/flr-cli/assets/15608631/b20a79f1-4688-4d5f-ab4d-ebe89713f133)

**Comment by Ziven-n** [comment]
![截屏2023-11-16 15 39 40](https://github.com/Fly-Mix/flr-cli/assets/15608631/252a9012-6a0f-408d-a5dc-2b7bbc8bc3c7)

**Comment by Ziven-n** [comment]
![截屏2023-11-16 15 41 27](https://github.com/Fly-Mix/flr-cli/assets/15608631/8df62ada-573d-4536-a953-a900f1b01f76)

**Comment by Ziven-n** [comment]
如果我用vscode的flr生成的是正常的没有/的
如果我用命令行flr run生成的就是带/的，很奇怪

**Comment by YK-Unit** [comment]
> 如果我用vscode的flr生成的是正常的没有/的 如果我用命令行flr run生成的就是带/的，很奇怪

两个项目的实现有一点的差异。目前我这边用 flr-cli 没能复现你的问题，你那边能搞个可复现的 demo 工程，方便我这边查问题不？

**Comment by Ziven-n** [comment]
> 两个项目的实现有一点的差异。目前我这边用 flr-cli 没能复现你的问题，你那边能搞个可复现的 demo 工程，方便我这边查问题不？

问题已解决，我在配置的时候路径里多了一个/
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
  - assets/videos/
  - assets/images/
  fonts:
  - assets/fonts
