### ISSUE TITLE
fonts没有自动生成

### ISSUE THREAD

**Issue by chenjie1219** [Fly-Mix/flr-cli#5]

**Comment by YK-Unit** [comment]
请问使用的是 flr-cli 哪个版本？
PS：目前最新版 v3.2.0 已经支持 `R.fontFamily` 的生成。

**Comment by chenjie1219** [comment]
![image](https://user-images.githubusercontent.com/16828878/173275297-5025d6b4-4469-49d4-a119-fff4faaee38d.png)

**Comment by YK-Unit** [comment]
> ![image](https://user-images.githubusercontent.com/16828878/173275297-5025d6b4-4469-49d4-a119-fff4faaee38d.png)

可以提供下其他额外信息吗，包括但是不限于：
- 开发机的操作系统信息
- flutter版本信息
- 工程demo链接

**Comment by chenjie1219** [comment]
[r_test.zip](https://github.com/Fly-Mix/flr-cli/files/8897899/r_test.zip)
操作系统 macOS Monterey
flutter版本3.0.2

**Comment by YK-Unit** [comment]
> [r_test.zip](https://github.com/Fly-Mix/flr-cli/files/8897899/r_test.zip) 操作系统 macOS Monterey flutter版本3.0.2

你这个字体资源存放目录和要扫描的字体资源目录路径声明不匹配导致的。

建议参考我们给的示例[flutter_hello_app](https://github.com/Fly-Mix/flutter_hello_app)进行调整：

<img width="351" alt="image" src="https://user-images.githubusercontent.com/4953353/174428459-32980555-94e5-465f-841d-c52ba7ca4cde.png">
