### ISSUE TITLE
M2芯片的Mac上执行命令后无法使用flr

### ISSUE THREAD

**Issue by Ziven-n** [Fly-Mix/flr-cli#9]

**Comment by Ziven-n** [comment]
@YK-Unit 在M2芯片的Mac pro上貌似无法使用flr，执行完

ziven@ZivendeMacBook-Pro demo % sudo gem install flr         
Password:
Successfully installed flr-3.2.0
Parsing documentation for flr-3.2.0
Done installing documentation for flr after 0 seconds
1 gem installed
ziven@ZivendeMacBook-Pro demo % flr init
zsh: command not found: flr
ziven@ZivendeMacBook-Pro demo % flr run
zsh: command not found: flr
ziven@ZivendeMacBook-Pro demo % 

demo是flutter项目

**Comment by YK-Unit** [comment]
这个看起来是 Ruby 在新系统下的环境兼容问题导致的，你可以试试这样安装：
```
sudo gem install -n /usr/local/bin flr
```

**Comment by Ziven-n** [comment]
> 这个看起来是 Ruby 在新系统下的环境兼容问题导致的，你可以试试这样安装：
> 
> ```
> sudo gem install -n /usr/local/bin flr
> ```

解决了，谢谢
